version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.2
    commands:
      - echo Installing Composer...
      - curl -sS https://getcomposer.org/installer | php
      - mv composer.phar /usr/local/bin/composer

  build:
    commands:
      - echo Installing dependencies...
      - composer install --no-dev
      - echo Build completed

artifacts:
  files:
    - '**/*'




